=== jasenzhangj/codegen/src/com/hitao/codegen/configs/dao/codegen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.hitao.com/codegen" xmlns="http://www.hitao.com/codegen"
	elementFormDefault="qualified">

	<xsd:attributeGroup name="name_class">
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="class" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="genericType" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="concreteClass" type="xsd:string" use="optional"></xsd:attribute>
	</xsd:attributeGroup>

	<xsd:attributeGroup name="parameter_attribute">
		<xsd:attribute name="modify" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attributeGroup ref="name_class"></xsd:attributeGroup>
	</xsd:attributeGroup>

	<xsd:attributeGroup name="field_attribute">
		<xsd:attribute name="value" type="xsd:string" use="optional"
			default="null"></xsd:attribute>
		<xsd:attributeGroup ref="parameter_attribute"></xsd:attributeGroup>
	</xsd:attributeGroup>


	<xsd:attributeGroup name="interface_class_attribute">
		<xsd:attribute name="modify" type="xsd:string" use="optional"
			default="public"></xsd:attribute>
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="package" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="extends" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="genericType" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="concreteClass" type="xsd:string" use="optional"></xsd:attribute>
	</xsd:attributeGroup>

	<xsd:attributeGroup name="implement_class_attribute">
		<xsd:attribute name="modify" type="xsd:string" use="optional"
			default="public"></xsd:attribute>
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="package" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="extends" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="implements" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="genericType" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="concreteClass" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="table" type="xsd:string" use="optional"></xsd:attribute>
	</xsd:attributeGroup>

	<xsd:attributeGroup name="method_attribute">
		<xsd:attribute name="modify" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="returnType" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="returnComment" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="override" type="xsd:boolean" use="optional"></xsd:attribute>
	</xsd:attributeGroup>


	<xsd:element name="field">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="comment" maxOccurs="1" minOccurs="0"></xsd:element>
			</xsd:sequence>
			<xsd:attributeGroup ref="field_attribute"></xsd:attributeGroup>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="parameter">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="comment" maxOccurs="1"></xsd:element>
			</xsd:sequence>
			<xsd:attributeGroup ref="parameter_attribute"></xsd:attributeGroup>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="throwException">
		<xsd:complexType>
			<xsd:all>
				<xsd:element ref="comment" minOccurs="0" maxOccurs="1"></xsd:element>
			</xsd:all>
			<xsd:attribute name="class" use="required"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="body" type="xsd:string" />

	<xsd:element name="method">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="comment" maxOccurs="1" minOccurs="0"></xsd:element>
				<xsd:element ref="parameter" maxOccurs="unbounded" minOccurs="0"></xsd:element>
				<xsd:element ref="throwException" maxOccurs="unbounded" minOccurs="0"></xsd:element>
				<xsd:element ref="body" maxOccurs="1" minOccurs="0"></xsd:element>
			</xsd:sequence>
			<xsd:attributeGroup ref="method_attribute"></xsd:attributeGroup>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="comment" type="xsd:string" />

	<xsd:element name="import">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="importblock" type="xsd:string" />

	<xsd:complexType name="implement_class">
			<xsd:sequence>
				<xsd:element ref="import" maxOccurs="unbounded" minOccurs="0"></xsd:element>
				<xsd:element ref="importblock" maxOccurs="unbounded" minOccurs="0"></xsd:element>
				<xsd:element ref="comment" maxOccurs="1" minOccurs="0"></xsd:element>
				<xsd:element ref="field" maxOccurs="unbounded" minOccurs="0"></xsd:element>
				<xsd:element ref="method" maxOccurs="unbounded" minOccurs="0"></xsd:element>
			</xsd:sequence>
			<xsd:attributeGroup ref="implement_class_attribute"></xsd:attributeGroup>
	</xsd:complexType>

	<xsd:complexType name="interface_class">
			<xsd:sequence>
				<xsd:element ref="import" maxOccurs="unbounded" minOccurs="0"></xsd:element>
				<xsd:element ref="importblock" maxOccurs="unbounded" minOccurs="0"></xsd:element>
				<xsd:element ref="comment" maxOccurs="1" minOccurs="0"></xsd:element>
				<xsd:element ref="field" maxOccurs="unbounded" minOccurs="0"></xsd:element>
				<xsd:element ref="method" maxOccurs="unbounded" minOccurs="0"></xsd:element>
			</xsd:sequence>
			<xsd:attributeGroup ref="interface_class_attribute"></xsd:attributeGroup>
	</xsd:complexType>

	<xsd:element name="dao" type="interface_class" />
	<xsd:element name="daoimpl" type="implement_class" />
	<xsd:element name="manager" type="interface_class" />
	<xsd:element name="managerimpl" type="implement_class" />
	<xsd:element name="ao" type="interface_class" />
	<xsd:element name="aoimpl" type="implement_class" />
	<xsd:element name="do" type="implement_class" />
	<xsd:element name="class" type="implement_class" />

	<xsd:element name="daogen">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="dao" minOccurs="1" maxOccurs="1"></xsd:element>
				<xsd:element ref="daoimpl" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="manager" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="managerimpl" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="ao" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="aoimpl" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="do" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="class" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="codegen">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="daogen" maxOccurs="unbounded"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== jasenzhangj/codegen/config/hitao/test.codegen.dao.xml
<?xml version="1.0" encoding="UTF-8"?>
<codegen xmlns="http://www.hitao.com/codegen" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hitao.com/codegen ../../src/codegen.xsd ">
	<daogen>
		<dao name="UserOperationLogDAO&lt;E extends UserOperationLogDO &gt;"
			package="com.taobao.hitao.camel.dao.log">
			<import>com.taobao.hitao.camel.dataobject.log.UserOperationLogDO</import>
			<comment>增加用户操作管理接口</comment>
			<method modify="public" name="addUserOperationLog" returnType="int">
				<comment>增加用户操作日志</comment>
				<parameter
					class="E"
					name="argUserOperationLogDO">
					<comment>日志信息对象</comment>
				</parameter>
				<throwException
					class="com.taobao.common.dao.persistence.exception.DAOException">
					<comment>dao异常</comment>
				</throwException>
			</method>
		</dao>

<!--		<manager package="com.taobao.hitao.camel.biz.manager.log"-->
<!--			name="UserOperationLogManager&lt;E extends UserOperationLogDO&gt;">-->
<!--			<import>com.hitao.codegen.UserOperationLogDO</import>-->
<!--			<comment>用户操作日志管理</comment>-->
<!--			<method modify="public" name="addUserOperationLog" returnType="int">-->
<!--				<comment>增加用户操作日志</comment>-->
<!--				<parameter class="E" name="argUserOperationLogDO">-->
<!--					<comment>日志信息对象</comment>-->
<!--				</parameter>-->
<!--			</method>-->
<!--		</manager>-->

<!--		<managerimpl package="com.taobao.hitao.camel.biz.manager.log.impl"-->
<!--			name="UserOperationLogManager" implements="com.taobao.hitao.camel.biz.manager.log.UserOperationLogManager&lt;DefaultUserOperationLogDO&gt; ">-->
<!--			<import>com.taobao.hitao.camel.biz.manager.log.UserOperationLogManager</import>-->
<!--			<import>com.taobao.common.dao.persistence.exception.DAOException</import>-->
<!--			<comment>用户操作日志管理</comment>-->
<!--			<field name="log" class="org.apache.commons.logging.Log"></field>-->
<!--			<field name="userOperationLogDAO"-->
<!--				class="com.taobao.hitao.camel.dao.log.UserOperationLogDAO"></field>-->
<!--			<method modify="public" name="addUserOperationLog" returnType="int">-->
<!--				<comment>增加用户操作日志</comment>-->
<!--				<parameter-->
<!--					class="com.taobao.hitao.camel.dataobject.log.DefaultUserOperationLogDO"-->
<!--					name="argUserOperationLogDO">-->
<!--					<comment>日志信息对象</comment>-->
<!--				</parameter>-->
<!--				<body>-->
<!--				<![CDATA[-->
<!--				try {-->
<!--					return userOperationLogDAO-->
<!--							.addUserOperationLog(argUserOperationLogDO);-->
<!--				} catch (DAOException e) {-->
<!--					log.error("插入日志异常:"+argUserOperationLogDO,e);-->
<!--				}-->
<!--				return 0;-->
<!--				]]>-->
<!--				</body>-->
<!--			</method>-->
<!--		</managerimpl>-->
<!---->
		<do package="com.taobao.hitao.camel.dataobject.log" name="DefaultUserOperationLogDO"
			table="hitao_user_test">
			<comment>用户操作日志DO</comment>
<!--			<field name="id" class="long" modify="private">-->
<!--				<comment>日志ID</comment>-->
<!--			</field>-->
<!--			<field name="userId" class="long" modify="private">-->
<!--				<comment>用户ID</comment>-->
<!--			</field>-->
<!--			<field name="userName" class="String" modify="private">-->
<!--				<comment>用户名称</comment>-->
<!--			</field>-->
<!--			<field name="operationType" class="int" modify="private" value="2;">-->
<!--				<comment>用户操作类型</comment>-->
<!--			</field>-->
<!--			<field name="itemId" class="String" modify="private">-->
<!--				<comment>用户操作实例ID</comment>-->
<!--			</field>-->
<!--			<field name="opertaionDate" class="java.util.Date" modify="private"-->
<!--				value="new Date()">-->
<!--				<comment>用户操作日期</comment>-->
<!--			</field>-->
<!--			<field name="ipAddress" class="String" modify="private"-->
<!--				value="&quot;zhangjun&quot;">-->
<!--				<comment>用户Ip地址</comment>-->
<!--			</field>-->
		</do>

	</daogen>
</codegen>
